# Use a imagem oficial do Node.js (ou a base que você utiliza)
FROM node:18-alpine

# Configuração do diretório de trabalho
WORKDIR /app

# Instala dependências para o Git e SSH
RUN apk add --no-cache git openssh

# Copia a chave privada para o container
COPY .docker/id_docker_rsa /root/.ssh/id_docker_rsa

# Configura permissões seguras para a chave
RUN chmod 600 /root/.ssh/id_docker_rsa

# Configura o SSH para usar essa chave específica
RUN echo "Host github.com\n\tIdentityFile /root/.ssh/id_docker_rsa\n\tStrictHostKeyChecking no\n" >> /root/.ssh/config

# Clona o repositório diretamente no diretório de trabalho sem criar uma pasta
RUN git clone git@github.com:Malnati/node-gen-fre.git .

# Instala as dependências da aplicação
RUN npm install

# Constrói a aplicação para produção
RUN npm run build

# Expõe a porta que o Vite irá utilizar para servir a aplicação
EXPOSE 5173

# Comando para iniciar a aplicação em modo de preview para produção
CMD ["npm", "run", "serve"]
