# Use a imagem oficial do Node.js (ou a base que você utiliza)
FROM node:18-alpine

# Configuração do diretório de trabalho
WORKDIR /app

# Instala dependências para o Git e SSH
RUN apk add --no-cache git openssh

# Copia a chave privada para o container
COPY .docker/id_docker_rsa /root/.ssh/id_docker_rsa

# Configura permissões seguras para a chave
RUN chmod 600 /root/.ssh/id_docker_rsa

# Copia o arquivo config para o diretório SSH
COPY .docker/ssh_config /root/.ssh/config

# Adiciona a chave do GitHub ao known_hosts para evitar o erro de verificação do host
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts

# Verifique se a chave e a configuração estão corretas
RUN ls -la /root/.ssh
RUN ssh -T git@github.com || true

# Clona o repositório diretamente no diretório de trabalho sem criar uma pasta
RUN git clone git@github.com:Malnati/node-gen-fre.git /app

# Instala as dependências da aplicação
RUN npm install

# Constrói a aplicação para produção
RUN npm run build

# Expõe a porta que o Vite irá utilizar para servir a aplicação
EXPOSE 5173

# Comando para iniciar a aplicação em modo de preview para produção
CMD ["npm", "run", "serve"]
