# .docker/Dockerfile.sspa
FROM nginx:alpine

RUN apk add --no-cache bash nodejs npm

RUN mkdir -p /usr/share/nginx/html/css /usr/share/nginx/html/js /usr/share/nginx/html/data /usr/share/nginx/html/entity /opt/sspa

COPY .docker/sspa/dashboard.css /usr/share/nginx/html/css/dashboard.css
COPY .docker/sspa/app.js /usr/share/nginx/html/js/app.js
COPY .docker/sspa/index.html /usr/share/nginx/html/index.html
COPY .docker/sspa/sspa.conf /etc/nginx/conf.d/sspa.conf
COPY .docker/sspa/generate-projects-json.js /opt/sspa/generate-projects-json.js

RUN rm -f /etc/nginx/http.d/default.conf

EXPOSE 9000

CMD ["/bin/sh","-c","echo \"[sspa] Starting...\" && sed -i \"s/__SSPA_SKIP_AUTH__/${SSPA_SKIP_AUTH:-false}/g\" /usr/share/nginx/html/js/app.js && node /opt/sspa/generate-projects-json.js && echo \"[sspa] projects.json initialized\" && nginx -g \"daemon off;\""]
