// src/app/config/datasource.service.ts - generated by node-gen

import "reflect-metadata";
import { DataSource } from "typeorm";
import { Injectable } from "@nestjs/common";
import { EnvironmentService } from "./environment.service";
{{entityImports}}

/** Cache duration for TypeORM (1 year in milliseconds) */
export const cacheDuration = 31536000000;

@Injectable()
/** Service responsible for providing a configured DataSource instance */
export class DataSourceService {
  private readonly dataSource: DataSource;

  constructor(private readonly env: EnvironmentService) {
    this.dataSource = new DataSource({
      type: "postgres",
      host: env.getEnv().get<string>("DATABASE_HOST"),
      port: env.getEnv().get<number>("DATABASE_PORT"),
      database: env.getEnv().get<string>("DATABASE_NAME"),
      username: env.getEnv().get<string>("DATABASE_USER"),
      password: env.getEnv().get<string>("DATABASE_PASSWORD"),
      entities: [{{entitiesArray}}],
      synchronize: false,
      logging: true,
      cache: {
        type: "database", // Using TypeORM in-memory cache
        duration: cacheDuration,
      },
      // ssl: env.getEnv().get<boolean>("DATABASE_SSL")
      //   ? { rejectUnauthorized: false }
      //   : undefined,
    });
  }

  /** Returns the configured DataSource */
  getDataSource(): DataSource {
    return this.dataSource;
  }
}
