{{imports}}

// Generated by node-gen
/**
 * {{entityDescription}}
 *
 * Representa a tabela '{{tableName}}'.
 *
{{columnList}}
 */
@Entity('{{tableName}}')
export class {{pascalTableName}}Entity {
  {{columns}}
  {{relations}}

  {{customMethods}}
}
